### ISSUE TITLE
Can I set the Bot to hook in specific tables?

### ISSUE THREAD

**Issue by vinimlo** [mikeroneer/taigagram#2]
People at my team are complaining about the "annoying" messages. Can I set to a specific table?

**Comment by mikeroneer** [comment]
Hi @vinimlo,
unhappily this is not possible for now. I have already thought about the feature of filtering the hooks coming from taiga.io, since there's no possibilty in taiga to turn specific hooks on or off.

Which messages does your team consider "annoying"?

**Comment by vinimlo** [comment]
My team consider annoying the fact that every move at the project alerts the group. They think it would be better if it just sends a message when we create a new task. Can I do this manually? And, can I help you later in doing that "selector"?

**Comment by mikeroneer** [comment]
@vinimlo I'm sorry for the delay...unfortunately there was no time left for this project..

I would be glad if you could help doing that "selector", because there will be still quite less time left in the future. Can you contact me in a personal message on telegram to discuss further details?

**Comment by vinimlo** [comment]
Sure! My telegram is: @vinimlo 
Just contact me!
